# SPDX-License-Identifier: SSPL-1.0
# Copyright (c) 2023-present Banca d'Italia

#  _   __        __                 __
# | | / /__ ____/ /__ ________  ___/ /__
# | |/ / _ `/ _  / _ `/ __/ _ \/ _  / -_)
# |___/\_,_/\_,_/\_,_/\__/\___/\_,_/\__/
# 
# @file Antora playbook for Vadacode manual, 
# required to test the documentation locally.

site:
  title: Vadacode manual
content:
  sources:
    - url: ../../
      start_path: docs/manual/
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
antora:
  extensions:
    - require: "@antora/lunr-extension"
